module NeanesGlyph exposing (Glyph, decoder, glyphFile)

{-| Generates one `Html msg` helper per glyph in the Neanes font, sourced from
the SBMuFL `glyphnames.json` shipped with byzhtml:
<https://github.com/neanes/byzhtml/blob/master/assets/fonts/sbmufl/glyphnames.json>

Each generated helper delegates to a shared `glyph` function so the wrapper
markup lives in exactly one place.

-}

import Elm
import Elm.Annotation as Type
import Gen.Char
import Gen.Html
import Gen.Html.Attributes
import Gen.String
import Json.Decode as Decode exposing (Decoder)


type alias Glyph =
    { name : String
    , codepoint : String
    , alternateCodepoint : Maybe String
    }


{-| Decodes the `glyphnames.json` object, preserving the source key order.
-}
decoder : Decoder (List Glyph)
decoder =
    Decode.keyValuePairs
        (Decode.map2 Tuple.pair
            (Decode.field "codepoint" Decode.string)
            (Decode.maybe (Decode.field "alternateCodepoint" Decode.string))
        )
        |> Decode.map
            (List.map
                (\( name, ( codepoint, alternateCodepoint ) ) ->
                    { name = name
                    , codepoint = codepoint
                    , alternateCodepoint = alternateCodepoint
                    }
                )
            )


glyphFile : List Glyph -> Elm.File
glyphFile glyphs =
    Elm.file [ "NeanesGlyph" ]
        (Elm.comment "Generated by `npm run codegen` from byzhtml's SBMuFL glyphnames.json. Do not edit by hand."
            :: glyphDeclaration
            :: List.filterMap glyphHelper glyphs
        )


htmlAnnotation : Type.Annotation
htmlAnnotation =
    Gen.Html.annotation_.html (Type.var "msg")


{-| `glyph codepoint = span [ class "font-neanes" ] [ text (String.fromChar (Char.fromCode codepoint)) ]`
-}
glyphDeclaration : Elm.Declaration
glyphDeclaration =
    Elm.fn ( "codepoint", Just Type.int )
        (\codepoint ->
            Gen.Html.span
                [ Gen.Html.Attributes.class "font-neanes" ]
                [ Gen.Html.call_.text
                    (Gen.String.call_.fromChar (Gen.Char.call_.fromCode codepoint))
                ]
                |> Elm.withType htmlAnnotation
        )
        |> Elm.declaration "glyph"
        |> Elm.withDocumentation "Render an arbitrary codepoint in the Neanes font."


glyphHelper : Glyph -> Maybe Elm.Declaration
glyphHelper { name, codepoint, alternateCodepoint } =
    parseCodepoint codepoint
        |> Maybe.map
            (\code ->
                Elm.apply (Elm.val "glyph") [ Elm.hex code ]
                    |> Elm.withType htmlAnnotation
                    |> Elm.declaration name
                    |> Elm.withDocumentation (glyphDocs codepoint alternateCodepoint)
            )


glyphDocs : String -> Maybe String -> String
glyphDocs codepoint alternateCodepoint =
    case alternateCodepoint of
        Just alt ->
            codepoint ++ " (alternate: " ++ alt ++ ")"

        Nothing ->
            codepoint


{-| Parses `"U+E000"` into `0xE000`.
-}
parseCodepoint : String -> Maybe Int
parseCodepoint string =
    if String.startsWith "U+" string then
        String.dropLeft 2 string
            |> String.toUpper
            |> String.foldl
                (\char acc ->
                    Maybe.map2 (\total digit -> total * 16 + digit) acc (hexDigit char)
                )
                (Just 0)

    else
        Nothing


hexDigit : Char -> Maybe Int
hexDigit char =
    let
        code =
            Char.toCode char
    in
    if Char.isDigit char then
        Just (code - Char.toCode '0')

    else if code >= Char.toCode 'A' && code <= Char.toCode 'F' then
        Just (code - Char.toCode 'A' + 10)

    else
        Nothing
